query getCategoryTree($rootNodeId: ID!) {
  category(id: $rootNodeId) {
    ...Category
    ...CategoryRecursive
  }
}

query getCategory($id: ID!) {
  category(id: $id) {
    ...Category
  }
}

fragment Category on Category {
  id
  name
  color
  slug
  metadata
  image {
    url
    srcset
  }
  items {
    ...Article
  }
}

fragment CategoryRecursive on Category {
  children {
    ...Category
    children {
      ...Category
      children {
        ...Category
        children {
          ...Category
          children {
            ...Category
            children {
              ...Category
              children {
                ...Category
                children {
                  ...Category
                  children {
                    ...Category
                    children {
                      ...Category
                      children {
                        ...Category
                        children {
                          ...Category
                          children {
                            ...Category
                            children {
                              ...Category
                              children {
                                ...Category
                              }
                            }
                          }
                        }
                      }
                    }
                  }
                }
              }
            }
          }
        }
      }
    }
  }
}
