query getNationalCompetition($competitionSlug: String!, $skillSlug: String!) {
  nationalCompetition(competitionSlug: $competitionSlug, skillSlug: $skillSlug) {
    ...NationalCompetition
  }
}

fragment FlatNationalCompetition on NationalCompetition {
  id
  name
  competitionId
  skillId
  isActive
  registrationEndsAt
  competitionEndsAt
  createdAt
  updatedAt
  ageLimit
  article {
    ...Article
  }
}

fragment NationalCompetition on NationalCompetition {
  ...FlatNationalCompetition
  skill {
    ...Skill
  }
  competition {
    ...Competition
  }
}
