query getSponsor($articleSlug: String!) {
  sponsor(articleSlug: $articleSlug) {
    ...SponsorDetail
  }
}

query getSponsors($take: Int, $skip: Int) {
  sponsors(take: $take, skip: $skip) {
    data {
      ...Sponsor
    }
    pageInfo {
      ...PageInfo
    }
  }
}

fragment Sponsor on Sponsor {
  id
  name
  homepageUrl
  image {
    srcset
    url
  }
  article {
    ...Article
  }
}

fragment SponsorDetail on Sponsor {
  ...Sponsor
  skills {
    ...Skill
  }
  image {
    srcset
  }
}
